name: persistent_window_manager_example
description: Demonstrates persistent_window_manager on Windows, macOS and Linux.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_window_manager:
    path: ../
  hydrated_bloc: ^11.0.0
