name: persistent_window_manager_example
description: Demonstrates how to use persistent_window_manager.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_window_manager:
    path: ../
  hydrated_bloc: ^11.0.0
  path_provider: ^2.1.6
